name: Test SlothShield Dashboard

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports
      run: |
        python -c "import streamlit; import pandas; import numpy; import sklearn; import scapy; import plotly; print('All imports successful')"
    
    - name: Test model loading
      run: |
        python -c "
        import joblib
        import os
        if os.path.exists('results/best_model.pkl'):
            model = joblib.load('results/best_model.pkl')
            scaler = joblib.load('results/scaler.pkl')
            selector = joblib.load('results/feature_selector.pkl')
            print('Model files loaded successfully')
        else:
            print('Model files not found')
        "
    
    - name: Test dashboard syntax
      run: |
        python -m py_compile slothshield_dashboard.py
        echo "Dashboard syntax is valid"
